###

GET http://localhost

###

###
GET http://localhost/api/user/time
###


###
GET http://localhost/api/user/demo
###



###
GET http://localhost/api/user/time
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODM5MjA0MzcsImV4cCI6MTU4MzkzMTIzN30.4YjZ52G4Q2wNZCIlZ3U_6p-BSVYNcvc_NGZipnF5ECo
###


###
POST http://localhost/api/user/register
###

###
POST http://localhost/api/user/login
Content-Type: application/json

{
    "username":"ccc",
    "password":"ccc"
}
###


###
POST http://localhost/api/user/register
Content-Type: application/json

{
    "username":"ccc",
    "password":"ccc"
}
###



