###

GET http://localhost

###

###
GET http://localhost/api/user/time
###


###
GET http://localhost/api/user/demo
###



###
GET http://localhost/api/user/time
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODM5MjA0MzcsImV4cCI6MTU4MzkzMTIzN30.4YjZ52G4Q2wNZCIlZ3U_6p-BSVYNcvc_NGZipnF5ECo
###


###
POST http://localhost/api/user/register
###






### login USER
POST http://localhost/api/user/login
Content-Type: application/json

{
    "username":"ccc",
    "password":"ccc"
}
###


### login USER
POST http://localhost/api/user/login
Content-Type: application/json

{
    "username":"aaa",
    "password":"aaa"
}
###


### GET BOOKLIST
GET http://localhost/api/booklist/getbooklist
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlhdCI6MTU4NDUxOTI4MiwiZXhwIjoxNjcwOTE5MjgyfQ.AkbsmVhNkWqIw4L4F9avXTdXuHeMHjmp8psnVUfccQQ

###



### GET UNFINISHED BOOKLIST
GET http://localhost/api/booklist/getunfinishedbooklist
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlhdCI6MTU4NDUxOTI4MiwiZXhwIjoxNjcwOTE5MjgyfQ.AkbsmVhNkWqIw4L4F9avXTdXuHeMHjmp8psnVUfccQQ

###




### ADD USER
POST http://localhost/api/user/register
Content-Type: application/json

{
    "username":"nnn",
    "password":"nnn"
}
###

### CREATE BOOK
POST http://localhost/api/booklist/addbook
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlhdCI6MTU4NDI1NTUyMCwiZXhwIjoxNTg0MjY2MzIwfQ.u8F0L_qg_H7VX2gq9SyxXo1ortKdEzRFTe9GxSXmLSY
Content-Type: application/json

{
    "title":"5555",
    "author":"5555"
}
###

### CREATE BOOK
DELETE  http://localhost/api/booklist/deletebook/5e6ce5ab31567c0c2c323155
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlhdCI6MTU4NDE5MTA2MiwiZXhwIjoxNTg0MjAxODYyfQ.YCbLLTAvqcS8HnbdfVkcw09bE_YVUYVvey2YhvZysZU

###

### update BOOK
PUT  http://localhost/api/booklist/updatebook/5e6ce5ab31567c0c2c323155
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlhdCI6MTU4NDE5MTA2MiwiZXhwIjoxNTg0MjAxODYyfQ.YCbLLTAvqcS8HnbdfVkcw09bE_YVUYVvey2YhvZysZU

###
GET http://localhost/api/booklist/download/1585651560444
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNjYyIsImlhdCI6MTU4NTY1MTQyOSwiZXhwIjoxNjcyMDUxNDI5fQ.1BpCuxnETU9mDUXpKVlyXbEsbjzkcTQUNisqXFu6rSM

###

GET http://localhost/api/booklist/download/1585651560444



###



###

GET http://localhost/api/booklist/deleteAllFile



###



1584358223127